### ISSUE TITLE
Encounter an error when running the GPU version of FSM in Pangolin

### ISSUE THREAD

**Issue by hlj2546** [chenxuhao/GraphMiner#3]
After running `make` in /src/pangolin/fsm, encounter an error when running `./bin/pangolin/./fsm_base ./inputs/citeseer/graph 3 100` as the tips.
The running details are as follows:

max_size = 3
min_support = 100
Number of unique labels: 6
|V| 3312 |E| 9072
Found 1 devices
  Device[0]: NVIDIA GeForce GTX 1080 Ti
  Compute capability: 6.1
  Warp size: 32
  Total # SM: 28
  Total # CUDA cores: 3584
  Total amount of shared memory per block: 49152 bytes
  Total # registers per block: 65536
  Total amount of constant memory: 65536 bytes
  Total global memory: 10.9 GB
  Memory Clock Rate: 5.25 GHz
  Memory Bus Width: 352 bits
  Peak Memory Bandwidth: 484.44 GB/s

error 1: Cuda error in file '../../../include/pangolin_gpu/../graph_gpu.h' in line 108 : invalid argument.

which corresponds to `CUDA_SAFE_CALL(cudaMemcpy(d_labels_frequency, hg.get_label_freq_ptr(), (num_vertex_classes+1) * sizeof(vidType), cudaMemcpyHostToDevice));`
after reading the source code, I found that the use of `hg.get_label_freq_ptr()` after `labels_frequency_.clear();` may be the cause of the problem. But  I have no idea how to modify it to make the program run properly.
Could you help me to solve this problem?
Best regards.

**Comment by chenxuhao** [comment]
Hi, 

I have fixed this bug. Let me know if you have further issues. Thanks!
